### ISSUE TITLE
Awesome. Can you add a Gradio demo which has training as well for better quality?

### ISSUE THREAD

**Issue by FurkanGozukara** [btsmart/splatt3r#10]
Awesome. Can you add a Gradio demo which has training as well for better quality?

Thank you so much

**Comment by btsmart** [comment]
Hello,

Are you suggesting adding a post-processing step which takes the generated Gaussian Splat, and then performs regular 3DGS training using the two input views as supervision? I would be very keen to see the results from this process, but I do not currently plan to implement per-scene training procedures in this repo.

There are works such as InstantSplat (https://instantsplat.github.io/) and Wild Gaussian Splatting (https://github.com/nerlfield/wild-gaussian-splatting) which initialize point clouds from DUSt3R predictions and optimize them using 3DGS and see very good results. I suspect our results would be very similar, perhaps with slightly faster convergence because our Gaussians would be better initialized.
