### ISSUE TITLE
The Gradio demo can only upload one image

### ISSUE THREAD

**Issue by cwwjyh** [btsmart/splatt3r#25]
Great work! The Gradio demo can only upload one image. Could you open another interface to upload a second image?
![1727101614877](https://github.com/user-attachments/assets/7ebdd5c7-1e56-41fb-adf3-5fa34fc30209)

**Comment by btsmart** [comment]
Hello @cwwjyh,

The demo should allow you to upload two images, but you need to do so at the same time. If you have the file selector open, you should be able to select two images, such as by holding down control or shift, and then uploading them. Alternatively, you should be able to select two files and then drag them together into the file upload region.

Hope this helps, let me know if you are still running into issues. I am currently using the Gradio gallery element because it works better on iOS, but I can switch to a file uploading element which might behave a little nicer on some devices.

**Comment by cwwjyh** [comment]
thank you very much! I get it








 ----------Reply to Message----------
 On Thu, Sep 26, 2024 19:30 PM Brandon ***@***.***&gt; wrote:

  

 
Hello @cwwjyh,
 
The demo should allow you to upload two images, but you need to do so at the same time. If you have the file selector open, you should be able to select two images, such as by holding down control or shift, and then uploading them. Alternatively, you should be able to select two files and then drag them together into the file upload region.
 
Hope this helps, let me know if you are still running into issues. I am currently using the Gradio gallery element because it works better on iOS, but I can switch to a file uploading element which might behave a little nicer on some devices.
