### ISSUE TITLE
About ScanNet++ dataset code for retraining pixelSplat

### ISSUE THREAD

**Issue by sunboy0617** [btsmart/splatt3r#29]
Hi! First thank you for the open-sourcing of this wonderful project! I'm trying to reproduce the results of pixelSplat on ScanNet++, while I'm not sure about the detail settings of processing dataset under the codebase of pixelSplat. Would you mind to share the dataset code of ScanNet++ for retraining pixelSplat? Thanks in advance for your help!

**Comment by btsmart** [comment]
Hello @sunboy0617,

Sorry for the delayed reply, I was unfortunately very sick and busy over the past few weeks.

Please find attached the (messy) dataset code we used when training pixelSplat on ScanNet++. GitHub does not seem to support uploading .py files, so I have renamed it to a .txt file. Alongside this dataset code we also modified the training procedure so that the training schedules were the same, and this file is dependent on some changes we made to pixelSplat's augmentation shims to support depth.

If you are able to establish a more competitive baseline for pixelSplat, please let us know!

[dataset_scannetpp.txt](https://github.com/user-attachments/files/17611072/dataset_scannetpp.txt)

**Comment by sunboy0617** [comment]
Thanks for your reply! I will try it later.
